### ISSUE TITLE
Profile posts missing when directly visiting profiles in additional local timelines. 

### ISSUE THREAD

**Issue by Bexxia** [Dimillian/IceCubesApp#175]
When viewing an additional local timeline, and directly tapping on a user avatar, the message “an error occurred” is displayed instead of their posts. Pressing retry does not load them. 

Tapping a post in the timeline and then tapping the user avatar loads their profile with posts as normal. So does searching for their username.

**Comment by Dimillian** [comment]
I think it's been solved in the new version.

**Comment by Momentric** [comment]
This issue is still present in 1.5.10. The user's profile photo and description are loaded, but posts are not. An error message is displayed and pressing retry never works.

However, if you open the user's post on a remote timeline and then click their profile it works fine.
