### ISSUE TITLE
Bug: Hashtags not displayed 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1775]
## Environment:
 - OS: iOS 17.2
 - IceCubesApp version: 1.9.18
 
## Description
The hashtags in this post are not displayed. The hashtag at the top of the post, which shows why the post is in the timeline, is also missing.

https://libranet.de/display/0b6b25a8-5665-8bf1-55a6-90a670441999

![IMG_4822](https://github.com/Dimillian/IceCubesApp/assets/113246030/da3baf20-34f9-4adb-a57d-357d3c924a6a)

In the web client the hashtags are displayed below the image.
![IMG_4824](https://github.com/Dimillian/IceCubesApp/assets/113246030/4b1c7b5a-dc07-4119-b10d-0d70b1036aa7)

**Comment by Dimillian** [comment]
Fixed now

**Comment by blueturtleai** [comment]
In which version is it fixed? I just tried it in 1.10.8 and it still doesn’t work.

**Comment by Dimillian** [comment]
Hmmm are you sure? I see them on mine, it was fixed a while ago.

**Comment by blueturtleai** [comment]
I rechecked and still can’t see the #. I also deleted my cache and tried it with another account on a different instance (mastodon.social).

What caused the problem?

**Comment by Dimillian** [comment]
Can you send me a link to a faulty post. Because I thought you were talking about the tags at the top on the post on why a post would show in your timeline. But if you're talking about tags within a post, Ice Cubes will not show them at the bottom like on the web, but inline unless the author put them at the bottom on purpose.

**Comment by blueturtleai** [comment]
https://libranet.de/display/0b6b25a8-5665-8bf1-55a6-90a670441999

See my screenshots in the initial post. Neither the # at top, which indicates why the post in the timeline nor the # at the bottom were shown.

As it’s no longer in my timeline, I can’t test the first anymore. But when I open the post now, I still can’t see the # at the bottom (at least they are there on web). To test it, I enter the url in the search field of the explore tab.

**Comment by blueturtleai** [comment]
Here is another example, where the hashtags are missing in icecubes. The hashtag at the top, which shows why the post is in my timeline, is also missing again. In this case additionally the most of the post text is missing.

https://tv.filmfreedom.net/videos/watch/85584de0-3970-41dd-a6f9-4f68a67340d2

![IMG_4967](https://github.com/Dimillian/IceCubesApp/assets/113246030/0962ba93-e88a-4cd8-be54-6a4f16cb1d4b)

![IMG_4968](https://github.com/Dimillian/IceCubesApp/assets/113246030/2b764d5c-e071-4300-91f2-7646dbd5a765)

**Comment by blueturtleai** [comment]
Another example, where a post is in my feed, but the hashtag I follow, isn’t displayed at top. When I open the post in the browser, the #netflix, which I follow, is shown.

https://meine-url-ist-laenger-als-deine.de/was-machst-du-eigentlich-den-ganzen-tag-3-24/

**Comment by blueturtleai** [comment]
Didn’t happen to me for a long time -> close
