### ISSUE TITLE
Bug: Some Timelines and lists fail to load (varies by user/server)

### ISSUE THREAD

**Issue by opensiriusfox** [Dimillian/IceCubesApp#2309]
## Environment:

 - OS: 18.6.2
 
 - IceCubesApp version: 2.0
 

## Description

Following the update to 2.0, some timelines will never load, and others will load with a subset of posts from other timelines. Broken timelines cryptically indicate: An Error Occured, with no further information, and provide a button to try again.

In my case, I just the lists feature, and some of my lists work as expected, others never load (even after waiting 12 hours to see if something changed and manually clearing the media cache), and one sometimes shows posts but none of the posts shown are consistent with any of my lists.

The bug appears to have no relation to the list settings, list name (i.e. I have both broken and functional ASCII name only lists, and functional ones with non-Latin Unicode characters, not the order of the lists in the pinned view, nor if the lists are pinned or unpinned.

Manually trying to refresh simply refreshes the view and returns the same error again indefinitely.

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by opensiriusfox** [comment]
As one follow on detail. This bug also can (and in my case does) occur for the “local” and “notification” timelines. Reinstalling results in a different set of failed timelines, and all lists associated with my account no longer being available in any UI element other than embedded web views of my home server.

**Comment by Dimillian** [comment]
Yes. It's already fixed in main I believe but will get out in the 2.0.2

**Comment by opensiriusfox** [comment]
I just upgraded to 2.0.2 and the bug has persisted.

Errors persist through an uninstall and reinstall.

Is there some way I can enable debugging logs to help diagnose the root cause?

Given the changing nature of which timelines fail, I’m inclined to suspect this is something in the basic parser for individual posts.

**Comment by opensiriusfox** [comment]
My offer to help debug stands. The bug is manifesting as periodically failing to load the timeline, but earlier and sometimes later chunks load fine. This seems very likely to be a chunk of posts being misparsed due to the formatting of a single post in the chunk handed to the client.
