### ISSUE TITLE
Issue: Preview images not loading when expanding

### ISSUE THREAD

**Issue by chenew** [Dimillian/IceCubesApp#973]
## Environment:

 - OS: iOS 16.3.1
 - IceCubesApp version: 1.5.4
 - Instance is behind Cloudflare proxy

## Description

Preview images aren’t loading the originals when viewing from the timeline. Tapping on an image from the timeline opens up the preview window, but will be blank with the word “original” and the size of the image.

![0F684C6E-E684-4BB6-96E1-E5D4865DF818](https://user-images.githubusercontent.com/5931313/220233039-98233a88-da93-421a-adb3-05b25e499015.png)

**Comment by chenew** [comment]
If compression is enabled on Cloudflare, this error is reproducible. The fix that worked for me was disabling compression within Cloudflare.

1. Within Cloudflare, go to the site, then go to Speed > Optimization.
2. Toggle the Brotli switch to Off.

More info: https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-

Once compression was disabled, all preview images loaded the originals fine from the timeline.

**Comment by chenew** [comment]
Turns out Cloudflare's Brotili wasn't the issue. Still having issues with loading originals from the timeline preview images. Will continue investigating.

**Comment by chenew** [comment]
https://user-images.githubusercontent.com/5931313/220786363-3a3b1e72-929b-4b80-974c-f25dfdf610dc.MP4


Looked into this further on my server. Doesn't seem like a Cloudflare issue as I directly bypassed Cloudflare and still have issues with opening image previews from the timeline.

Logs under `/var/log/nginx/access.log` logs this when this issue is happening:
`[22/Feb/2023:23:22:43 +0000] "GET /media_proxy/109910863980207285/original HTTP/2.0" 302 176 "-" "IceCubesApp/1572 CFNetwork/1404.0.5 Darwin/22.3.0"` (notice the 302 redirect)

Logs under `/var/log/syslog` logs this:
```
Feb 22 23:22:43 bundle[956]: [34a60965-de7c-43a0-be56-7d13a51d0889] method=GET path=/media_proxy/109910863980207285/original format=*/* controller=MediaProxyControlle
r action=show status=302 duration=10.95 view=0.00 db=2.20 location=https://media.techy.social/cache/media_attachments/files/109/910/863/980/207/285/original/d52fb89b070076ac.png
```

So, Nginx issues a 302 redirect to https://media.techy.social/cache/media_attachments/files/109/910/863/980/207/285/original/d52fb89b070076ac.png, which is accessible, but IceCubesApp is possibly not recognizing the redirect.

**Comment by chenew** [comment]
This issue has been fixed. Observed in the Sidekiq logs `Terrapin::CommandNotFound`. Cause of this was imagemagick package was missing from the Sidekiq servers. More info described in this related issue: https://github.com/techy-social/support/issues/2.

**Comment by LorenAmelang** [comment]
OS: iOS 16.3.1
IceCubesApp version: 1.6.5 (haven't hit one in 1.6.6 yet...)

I'm still seeing those "original, data" pages when I tap links to some media. Haven't figured out a pattern to which links go there. 

What do I need to collect to report these properly? They're not on my own server...

**Comment by chenew** [comment]
@LorenAmelang, I run separate Sidekiq servers. My issue ended up being my Sidekiq servers didn’t have ImageMagick installed. If you have access to Sidekiq, check your logs to see if there’s any indication that images couldn’t be processed (mine said something like Terrapin couldn’t be found, which is related to imagemagick).
