### ISSUE TITLE
Bug: notifications with multiple accounts 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#981]
## Environment:
iOS 16.2, icecubes 1.5.5

## Description
I have several accounts and the screen was locked. I received a notification for an account, which wasn’t currently selected. I unlocked my phone, the notification indicator wasn’t red. I switched to the account which got a notification. The notification indicator was red and did show 1.

Does it behave like intended?
 
What happens, if I receive a notification when the phone is not locked and icecubes is the active app? Will the notification indicator turn red, so I know I got a new notification for another account?

**Comment by blueturtleai** [comment]
Now the same happened, when I currently used icecubes. So I had to check the accounts menu to notice, that I received a notification for another account.

**Comment by Dean151** [comment]
Might get fixed with c4daa739327a7c5b68ebd7935b4d4adf7539708e

**Comment by blueturtleai** [comment]
@Dean151 Do I guess right, the mentioned commit is included in 1.5.7? If so, the problem is unfortunately not solved.

I used the app and received 2 notifications to another account. The only way to know about the notifications was opening the accounts menu. I think, that’s not the way it should work.

**Comment by Dimillian** [comment]
So adding a badge on the top avatar if any other account than the current one have a notification could solve the issue right?

**Comment by blueturtleai** [comment]
Fixed by the new badge.
